"""
core/cost_dashboard.py — Visual cost reporting (v20 NEW)
=========================================================================
Generates human-readable Markdown dashboards from cost + quota data.

[Outputs]
- logs/dashboard_{YYYY-MM}.md — monthly cost summary
- logs/episode_breakdown_{NNN}.md — per-episode cost breakdown

[Usage]
After each episode:
    dashboard = CostDashboard(paths, quota_manager, cost_tracker)
    dashboard.write_episode_breakdown(episode_number, stages)
    dashboard.write_monthly_summary()

[What it tracks]
- Per-stage timing
- Per-service API costs
- Quota utilization curve (trend over episodes)
- Cost per episode trend
- Projected month-end costs
"""
from __future__ import annotations

import json
import logging
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)


class CostDashboard:
    """Markdown cost dashboards. Generates human-readable summaries."""

    def __init__(
        self,
        paths,  # PathsConfig
        quota_manager=None,
        cost_tracker=None,
    ) -> None:
        self._paths = paths
        self._quota = quota_manager
        self._cost = cost_tracker
        self._output_dir = Path(paths.logs)
        self._output_dir.mkdir(parents=True, exist_ok=True)

    def write_episode_breakdown(
        self,
        episode_number: int,
        stages: List,  # List[StageResult]
        api_calls: Optional[Dict[str, int]] = None,
        api_costs: Optional[Dict[str, float]] = None,
    ) -> str:
        """
        Write per-episode cost breakdown.
        Returns path to generated MD file.
        """
        path = self._output_dir / f"episode_{episode_number:03d}_breakdown.md"
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")

        # Compute totals
        total_duration = sum(getattr(s, 'duration_sec', 0) for s in stages)
        total_cost = sum((api_costs or {}).values())

        # Build stages table
        stages_md = "| Stage | Status | Duration |\n|-------|--------|----------|\n"
        for s in stages:
            status = "✅" if getattr(s, 'passed', False) else "❌"
            name = getattr(s, 'name', '?')
            dur = getattr(s, 'duration_sec', 0)
            stages_md += f"| {name} | {status} | {dur:.1f}s |\n"

        # Build API table
        api_md = ""
        if api_calls and api_costs:
            api_md = "| Service | Calls | Cost USD |\n|---------|-------|----------|\n"
            for svc in sorted(api_calls.keys()):
                calls = api_calls.get(svc, 0)
                cost = api_costs.get(svc, 0.0)
                api_md += f"| {svc} | {calls} | ${cost:.4f} |\n"
            api_md += f"| **Total** | — | **${total_cost:.4f}** |\n"

        # Quota snapshot
        quota_md = ""
        if self._quota:
            r = self._quota.report()
            quota_md = f"""
## Quota After This Episode

| Service | Used | Remaining | Utilization |
|---------|------|-----------|-------------|
| ElevenLabs | {r['elevenlabs']['used']:,} | {r['elevenlabs']['remaining']:,} | {r['elevenlabs']['utilization_percent']:.1f}% |
| Leonardo | {r['leonardo']['used']} | {r['leonardo']['remaining']} | {r['leonardo']['utilization_percent']:.1f}% |
| Anthropic | ${r['anthropic_spent_usd']:.4f} | — | — |

Episodes done this month: **{r['episodes_completed']}/{r['episodes_target']}**
"""

        content = f"""# Episode {episode_number} — Cost Breakdown

Generated: {timestamp}

## Summary
- Total Duration: **{total_duration:.1f}s**
- Total API Cost: **${total_cost:.4f}**

## Pipeline Stages

{stages_md}

## API Calls

{api_md if api_md else '_No API call data available_'}

{quota_md}

---

_Generated by QEEMA v20 CostDashboard_
"""
        try:
            path.write_text(content, encoding="utf-8")
            logger.info(f"📊 Episode breakdown saved: {path.name}")
        except OSError as e:
            logger.error(f"❌ Could not write breakdown: {e}")
        return str(path)

    def write_monthly_summary(self) -> str:
        """
        Write monthly cost + quota summary.
        Aggregates all episodes in current month.
        """
        if not self._quota:
            return ""

        report = self._quota.report()
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
        month = report["month"]
        path = self._output_dir / f"dashboard_{month}.md"

        # Read past episode breakdowns to compute trends
        episode_files = sorted(self._output_dir.glob("episode_*_breakdown.md"))
        episode_count = len(episode_files)

        # Read cost JSONL if available
        cost_log = self._output_dir / f"costs_{datetime.now().strftime('%Y-%m-%d')}.jsonl"
        cost_records: List[Dict] = []
        if cost_log.exists():
            try:
                with cost_log.open(encoding="utf-8") as f:
                    cost_records = [json.loads(line) for line in f if line.strip()]
            except (OSError, json.JSONDecodeError):
                pass

        total_cost_today = sum(r.get("cost_usd", 0) for r in cost_records)

        # Build cost-by-provider table
        by_provider: Dict[str, float] = {}
        for r in cost_records:
            p = r.get("provider", "unknown")
            by_provider[p] = by_provider.get(p, 0) + r.get("cost_usd", 0)

        provider_md = "| Provider | Cost USD |\n|----------|----------|\n"
        for p, c in sorted(by_provider.items(), key=lambda x: -x[1]):
            provider_md += f"| {p} | ${c:.4f} |\n"

        # Projected month-end
        eps_done = report["episodes_completed"]
        eps_target = report["episodes_target"]
        projected_total = total_cost_today * eps_target / max(eps_done, 1) if eps_done > 0 else 0

        # Status indicator
        el_pct = report["elevenlabs"]["utilization_percent"]
        leo_pct = report["leonardo"]["utilization_percent"]
        if el_pct > 90 or leo_pct > 90:
            status = "🔴 CRITICAL"
        elif el_pct > 70 or leo_pct > 70:
            status = "🟡 WARNING"
        else:
            status = "🟢 HEALTHY"

        content = f"""# Monthly Cost Dashboard — {month}

Generated: {timestamp}
Status: **{status}**

## Episodes Progress

```
{eps_done}/{eps_target} episodes completed
```

## Quota Utilization

| Service | Used | Total | % | Bar |
|---------|------|-------|---|-----|
| ElevenLabs | {report['elevenlabs']['used']:,} | {report['elevenlabs']['total']:,} | {el_pct:.1f}% | {self._bar(el_pct)} |
| Leonardo | {report['leonardo']['used']} | {report['leonardo']['total']} | {leo_pct:.1f}% | {self._bar(leo_pct)} |
| Anthropic | — | — | — | ${report['anthropic_spent_usd']:.4f} |

## Cost by Provider (Today)

{provider_md}

**Today's Total: ${total_cost_today:.4f}**

## Projections

- Average cost per episode: **${total_cost_today / max(eps_done, 1):.4f}**
- Projected month-end total: **${projected_total:.2f}**

## Episode Breakdowns

Generated: **{episode_count}** breakdown files

{self._format_episode_links(episode_files[:10])}

---

## Recommendations

{self._generate_recommendations(el_pct, leo_pct, eps_done, eps_target)}

---

_Generated by QEEMA v20 CostDashboard_
"""
        try:
            path.write_text(content, encoding="utf-8")
            logger.info(f"📊 Monthly dashboard saved: {path.name}")
        except OSError as e:
            logger.error(f"❌ Could not write dashboard: {e}")
        return str(path)

    @staticmethod
    def _bar(percent: float, width: int = 20) -> str:
        """Render an ASCII progress bar."""
        filled = int((percent / 100) * width)
        return "█" * filled + "░" * (width - filled)

    @staticmethod
    def _format_episode_links(files: List[Path]) -> str:
        if not files:
            return "_No breakdowns yet_"
        return "\n".join(f"- [{f.stem}](./{f.name})" for f in files)

    @staticmethod
    def _generate_recommendations(
        el_pct: float, leo_pct: float,
        eps_done: int, eps_target: int,
    ) -> str:
        recs: List[str] = []
        eps_remaining = eps_target - eps_done

        # Leonardo recommendations (matches status thresholds)
        if leo_pct >= 90:
            recs.append("🔴 **Leonardo critical**: switch to ECONOMY mode "
                       "(3 images/episode) immediately, or upgrade to Premium.")
        elif leo_pct >= 70:
            recs.append("🟡 **Leonardo elevated**: consider BALANCED mode "
                       "(5 images/episode) for remaining episodes.")

        # ElevenLabs recommendations (matches status thresholds)
        if el_pct >= 90:
            recs.append("🔴 **ElevenLabs critical**: enable Google TTS fallback "
                       "or skip remaining episodes until reset.")
        elif el_pct >= 70:
            recs.append("🟡 **ElevenLabs elevated**: shorter scripts recommended "
                       "for remaining episodes.")

        # Pacing check
        if eps_done > 0 and eps_target > 0:
            pace_ratio = eps_done / eps_target
            quota_ratio = max(el_pct, leo_pct) / 100
            if quota_ratio > pace_ratio + 0.15:
                recs.append(
                    f"🟡 **Burning quota faster than pace**: at {eps_done}/{eps_target} "
                    f"episodes you've used {max(el_pct, leo_pct):.0f}% of quota. "
                    f"Switch to BALANCED/ECONOMY for remaining {eps_remaining} episodes."
                )

        if not recs:
            recs.append("✅ All quotas healthy. Continue with current quality mode.")

        return "\n".join(f"- {r}" for r in recs)
