-- ============================================================
-- QEEMA (قيمة) — Curriculum Seed  (38 episodes)
-- Order: Al-Fatiha first, then Juz' Amma reversed (114 -> 78)
-- Run AFTER qeema_schema.sql, in Supabase > SQL Editor.
--
-- NOTE: This UPSERTs by episode_number and will REALIGN the
-- surah of every episode (including 1, 2, 17-20 you filled by hand)
-- to this single clean ordering. Titles are reset to NULL so the
-- pipeline regenerates them consistently as:
--     "سورة {الاسم}: رحلة {الثيمة}"
-- If you want to keep any hand-written title, tell me and I'll
-- exclude that row.
-- ============================================================

insert into public.episodes
  (episode_number, surah_number, surah_name, surah_name_en, ayah_start, ayah_end, title, status)
values
  (1,   1, 'الفاتحة',    'Al-Fatiha',     1, null, null, 'planned'),
  (2,  114, 'الناس',      'An-Nas',        1, null, null, 'planned'),
  (3,  113, 'الفلق',      'Al-Falaq',      1, null, null, 'planned'),
  (4,  112, 'الإخلاص',    'Al-Ikhlas',     1, null, null, 'planned'),
  (5,  111, 'المسد',      'Al-Masad',      1, null, null, 'planned'),
  (6,  110, 'النصر',      'An-Nasr',       1, null, null, 'planned'),
  (7,  109, 'الكافرون',   'Al-Kafirun',    1, null, null, 'planned'),
  (8,  108, 'الكوثر',     'Al-Kawthar',    1, null, null, 'planned'),
  (9,  107, 'الماعون',    'Al-Maun',       1, null, null, 'planned'),
  (10, 106, 'قريش',       'Quraysh',       1, null, null, 'planned'),
  (11, 105, 'الفيل',      'Al-Fil',        1, null, null, 'planned'),
  (12, 104, 'الهُمَزة',    'Al-Humazah',    1, null, null, 'planned'),
  (13, 103, 'العصر',      'Al-Asr',        1, null, null, 'planned'),
  (14, 102, 'التكاثر',    'At-Takathur',   1, null, null, 'planned'),
  (15, 101, 'القارعة',    'Al-Qariah',     1, null, null, 'planned'),
  (16, 100, 'العاديات',   'Al-Adiyat',     1, null, null, 'planned'),
  (17,  99, 'الزلزلة',    'Az-Zalzalah',   1, null, null, 'planned'),
  (18,  98, 'البينة',     'Al-Bayyinah',   1, null, null, 'planned'),
  (19,  97, 'القدر',      'Al-Qadr',       1, null, null, 'planned'),
  (20,  96, 'العلق',      'Al-Alaq',       1, null, null, 'planned'),
  (21,  95, 'التين',      'At-Tin',        1, null, null, 'planned'),
  (22,  94, 'الشرح',      'Ash-Sharh',     1, null, null, 'planned'),
  (23,  93, 'الضحى',      'Ad-Duha',       1, null, null, 'planned'),
  (24,  92, 'الليل',      'Al-Lail',       1, null, null, 'planned'),
  (25,  91, 'الشمس',      'Ash-Shams',     1, null, null, 'planned'),
  (26,  90, 'البلد',      'Al-Balad',      1, null, null, 'planned'),
  (27,  89, 'الفجر',      'Al-Fajr',       1, null, null, 'planned'),
  (28,  88, 'الغاشية',    'Al-Ghashiyah',  1, null, null, 'planned'),
  (29,  87, 'الأعلى',     'Al-Ala',        1, null, null, 'planned'),
  (30,  86, 'الطارق',     'At-Tariq',      1, null, null, 'planned'),
  (31,  85, 'البروج',     'Al-Buruj',      1, null, null, 'planned'),
  (32,  84, 'الانشقاق',   'Al-Inshiqaq',   1, null, null, 'planned'),
  (33,  83, 'المطففين',   'Al-Mutaffifin', 1, null, null, 'planned'),
  (34,  82, 'الانفطار',   'Al-Infitar',    1, null, null, 'planned'),
  (35,  81, 'التكوير',    'At-Takwir',     1, null, null, 'planned'),
  (36,  80, 'عبس',        'Abasa',         1, null, null, 'planned'),
  (37,  79, 'النازعات',   'An-Naziat',     1, null, null, 'planned'),
  (38,  78, 'النبأ',      'An-Naba',       1, null, null, 'planned')
on conflict (episode_number) do update set
  surah_number  = excluded.surah_number,
  surah_name    = excluded.surah_name,
  surah_name_en = excluded.surah_name_en,
  ayah_start    = excluded.ayah_start,
  ayah_end      = excluded.ayah_end,
  title         = null,        -- regenerated by the pipeline
  status        = 'planned';

-- Quick check after running:
-- select episode_number, surah_number, surah_name, status from public.episodes order by episode_number;
